version: '3.8'

services:
  postgres:
    build: .
    container_name: ecovibe_postgres
    environment:
      POSTGRES_DB: ecovibe
      POSTGRES_USER: ecovibeuser
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

